server:
  port: 8080
  address: 0.0.0.0

spring:
  application:
    name: AllService

  datasource:
    # Usa variáveis de ambiente — o Docker Compose passará elas automaticamente
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
      pool-name: allservice-pool
      max-lifetime: 600000
      connection-timeout: 100000
      connection-test-query: select 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema : public
        format_sql: true
        hikari:
          minimumIdle: 1
          maximumPoolSize: 10
        connection:
          isolation: 2
          autocommit: true
          driver_class: org.postgresql.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

logging:
  level:
    org.springframework.boot.context.config: DEBUG
    org.springframework.boot.autoconfigure.jdbc: DEBUG
    org.springframework.jdbc: DEBUG
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE
    org:
      hibernate:
        orm:
          connections:
            pooling: OFF
